classDiagram
  class EventMSG {
    debug
    error
    info
    warning
  }
  class deque {
    iterable : list
    maxlen : int
    append(x)
    appendleft(x)
    clear()
    copy()
    count(x)
    extend(iterable)
    extendleft(iterable)
    index(x, start, end)
    insert(i, x)
    pop()
    popleft()
    remove(value)
    reverse()
    rotate(n)
  }
  class DetectDuplicate {
    num_of_files
    get_json() str
  }
  class EventMSG {
    debug : str
    error : str
    info : str
    warning : str
  }
  class ExitStatus {
    name
  }
  class LogMessages {
    args
    dump
    elapse_time
    logfile
    num_of_files
    path
    python
    python_import
    result
  }
  class LoggingSetup {
    default_format : str
    default_level : str
    encoding : str
    file_format : str
    json_dump : str
    log_file : str
    simple_format : str
  }
  class MyFile {
    hash : Optional[str]
    path : str
    size : Optional[int]
    get_hash(blocksize: int) MyFile
    get_size(path: str) MyFile
  }
  class Enum {
    name()
    value()
  }
  class IntEnum {
  }
  class ReprEnum {
  }
  class NamedTuple {
  }
  EventMSG --|> NamedTuple
  ExitStatus --|> IntEnum
  LogMessages --|> NamedTuple
  LoggingSetup --|> NamedTuple
  MyFile --|> NamedTuple
  IntEnum --|> ReprEnum
  ReprEnum --|> Enum
  EventMSG --* LogMessages : logfile
  EventMSG --* LogMessages : args
  EventMSG --* LogMessages : path
  EventMSG --* LogMessages : python
  EventMSG --* LogMessages : python_import
  EventMSG --* LogMessages : dump
  EventMSG --* LogMessages : result
  EventMSG --* LogMessages : num_of_files
  EventMSG --* LogMessages : elapse_time
  deque --* DetectDuplicate : __hash
  deque --* DetectDuplicate : __files
